version: '3.8'
services:
  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - app-network

  node:
    image: super-app-jenkins-node
    container_name: super-app-jenkins-node
    build:
      context: ./node
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    networks:
      - app-network

  php:
    image: super-app-jenkins-php
    container_name: super-app-jenkins-php
    build:
      context: ./php
    ports:
      - '80:80'
    networks:
      app-network:
        ipv4_address: 172.28.1.2

  networks:
    app-network:
      driver: bridge
      ipam:
        config:
          - subnet: 172.28.1.0/24
