version: '3.8'
services:
  mysql:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      - superapp-network

  node:
    build:
      context: ./node
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    networks:
      - superapp-network

  php:
    build:
      context: ./php
    ports:
      - '80:80'
    networks:
      - superapp-network

networks:
  superpp-network:
    driver: bridge